-- AlterEnum
ALTER TYPE "OccasionType" ADD VALUE 'THANK_YOU';
ALTER TYPE "OccasionType" ADD VALUE 'TEAM_CELEBRATION';
ALTER TYPE "OccasionType" ADD VALUE 'COMPANY_CELEBRATION';
ALTER TYPE "OccasionType" ADD VALUE 'WORK_ANNIVERSARY';
ALTER TYPE "OccasionType" ADD VALUE 'RETIREMENT';
ALTER TYPE "OccasionType" ADD VALUE 'CONGRATULATIONS';
ALTER TYPE "OccasionType" ADD VALUE 'RECRUITING_ONBOARDING';
ALTER TYPE "OccasionType" ADD VALUE 'DEI_CELEBRATION';
ALTER TYPE "OccasionType" ADD VALUE 'OFFICE_COMPETITION';
ALTER TYPE "OccasionType" ADD VALUE 'DEPARTMENT_EVENT';
ALTER TYPE "OccasionType" ADD VALUE 'SYMPATHY';
ALTER TYPE "OccasionType" ADD VALUE 'EMPLOYEE_APPRECIATION';
ALTER TYPE "OccasionType" ADD VALUE 'HOLIDAY_CELEBRATION';
